title: Anh-Thi Dinh
description: I failed my way to success
baseurl: ""
url: ""

title-separator: "-"

google_analytics: UA-58921685-1
fb_app_id: "1150663561751902"

timezone: "Europe/Paris"
markdown: kramdown
mathjax: true
kramdown:
  input: GFM
highlighter: rouge
permalink: /:title

plugins:
  - jemoji
  - jekyll-sitemap
  # - jekyll-feed
  - jekyll-katex
  - jekyll-admin
  - jekyll-include-cache
  - jekyll-last-modified-at

sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
