version: '2.3'
services:
  jekyll:
    container_name: 'dat_local'
    image: jekyll/jekyll:4.1.0
    command: jekyll serve --config _config.yml,docker/_config.docker.yml -I
    volumes:
        - ..:/srv/jekyll
    ports:
        - 4000:4000
    working_dir: /srv/jekyll
    environment:
        - JEKYLL_ENV=docker